language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true export ROS_PARALLEL_JOBS="-j1 -l1"
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true export ROS_PARALLEL_JOBS="-j8"
script: source .travis/travis.sh
