r_hand:
  - link: "/r_gripper_palm_link"
    mesh: "package://pr2_description/meshes/gripper_v0/gripper_palm.dae"
    position: {x: -0.22, y: -0.027, z: 0.015}
  
  - link: "/r_gripper_l_finger_tip_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"
    #    position: {x: 0.168, y: 0.016, z: 0.0}
    position: {x: -0.054, y: -0.011, z: 0.015}

  - link: "/r_gripper_l_finger_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger.dae"
    #    position: {x: 0.077, y: 0.01, z: 0.0}
    position: {x: -0.143, y: -0.016, z: 0.015}

  - link: "/r_gripper_r_finger_tip_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"
    #    position: {x: 0.168, y: -0.016, z: 0.0}
    position: {x: -0.052, y: -0.043, z: 0.015}
    orient: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}

  - link: "/r_gripper_r_finger_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger.dae"
    #    position: {x: 0.077, y: -0.01, z: 0.0}
    position: {x: -0.143, y: -0.037, z: 0.015}
    orient: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}


l_hand:
  - link: "/l_gripper_palm_link"
    mesh: "package://pr2_description/meshes/gripper_v0/gripper_palm.dae"
    position: {x: -0.22, y: 0.027, z: 0.015}
  
  - link: "/l_gripper_l_finger_tip_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"
    #    position: {x: 0.168, y: 0.016, z: 0.0}
    position: {x: -0.054, y: 0.043, z: 0.015}

  - link: "/l_gripper_l_finger_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger.dae"
    #    position: {x: 0.077, y: 0.01, z: 0.0}
    position: {x: -0.143, y: 0.037, z: 0.015}

  - link: "/l_gripper_r_finger_tip_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"
    #    position: {x: 0.168, y: -0.016, z: 0.0}
    position: {x: -0.052, y: 0.011, z: 0.015}
    orient: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}

  - link: "/l_gripper_r_finger_link"
    mesh: "package://pr2_description/meshes/gripper_v0/l_finger.dae"
    #    position: {x: 0.077, y: -0.01, z: 0.0}
    position: {x: -0.143, y: 0.017, z: 0.015}
    orient: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}


